### ISSUE TITLE
Add Dataset: Elliptic

### ISSUE THREAD

**Issue by boersmamarcel** [AI4FinTech/FinTorch#31]
### Dataset Description
The Elliptic Data Set maps Bitcoin transactions to real entities belonging to licit categories (exchanges, wallet providers, miners, licit services, etc.) versus illicit ones (scams, malware, terrorist organizations, ransomware, Ponzi schemes, etc.). The task on the dataset is to classify the illicit and licit nodes in the graph.

### Tasks

- [ ] Download/Extraction Script
- [ ] Dataset Test
- [ ] Tutorial

### Additional Considerations
Dataset is hosted on Kaggle. We can use the Kaggle API to download the dataset (https://github.com/Kaggle/kaggle-api).
Note that users must authenticate themselves on Kaggle.

### license
This data set is distributed under the Creative CommonsAttribution-NonCommercial-NoDerivatives License 4.0 International.

### Submission Checklist

- [ ] I have followed the contribution guidelines.
- [ ] I have provided a thorough dataset description.
- [ ] My scripts and tests work as intended.
- [ ] The tutorial demonstrates dataset usage clearly.
