### ISSUE TITLE
Add Dataset: elliptic++

### ISSUE THREAD

**Issue by boersmamarcel** [AI4FinTech/FinTorch#34]
### Dataset Description

The Elliptic++ dataset consists of 203k Bitcoin transactions and 822k wallet addresses to enable both the detection of fraudulent transactions and the detection of illicit addresses (actors) in the Bitcoin network by leveraging graph data.

# References

https://github.com/git-disl/EllipticPlusPlus
https://dl.acm.org/doi/10.1145/3580305.3599803

### Tasks

- [ ] Download/Extraction Script
- [ ] Dataset Test
- [ ] Tutorial

### Additional Considerations

We will provide a download script that downloads the latest version of the dataset. The documentation will be referred to as an external source. 

### license

Don't know

### Submission Checklist

- [ ] I have read the contribution guidelines.
- [ ] I have provided a thorough dataset description.
- [ ] My scripts and tests work as intended.
- [ ] The tutorial demonstrates dataset usage clearly.
