### ISSUE TITLE
Add Model: GraphBEAN

### ISSUE THREAD

**Issue by boersmamarcel** [AI4FinTech/FinTorch#35]
### Model Description

The GraphBEAN model is an unsupervised machine learning system to detect anomalies within bipartite graphs. It analyzes interactions between two distinct groups (e.g., consumers and merchants), focusing on the attributes of individual nodes and the edges (connections) between them.

**Key Function**: Identifies unusual or suspicious behaviors that deviate from standard patterns, allowing for the detection of potentially fraudulent activities even without prior examples of such fraud.

**Details:** https://engineering.grab.com/graph-anomaly-model

[Interaction-Focused Anomaly Detection on Bipartite Node-and-Edge-Attributed Graphs.pdf](https://github.com/AI4FinTech/FinTorch/files/14628334/Interaction-Focused.Anomaly.Detection.on.Bipartite.Node-and-Edge-Attributed.Graphs.pdf)

### Tasks

- [ ] Model saving/loading script
- [ ] Model inference script (API or example)
- [ ] Model performance evaluation script
- [ ] Tutorial demonstrating usage

### license

yes

### Submission Checklist

- [ ] I have read the contribution guidelines.
- [ ] I have provided a detailed model description.
- [ ] All required scripts are provided, functional, and tested.
- [ ] I have clarified dependencies and hardware considerations.
- [ ] The tutorial is clear and demonstrates model usage.

**Comment by boersmamarcel** [comment]
Did a test run to trigger a release to the main pypi server, didn't work... will work on the original content of the issue.

**Comment by boersmamarcel** [comment]
https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/dense/linear.html#HeteroDictLinear

**Comment by boersmamarcel** [comment]
https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.data.HeteroData.html

**Comment by boersmamarcel** [comment]
https://medium.com/@pytorch_geometric/link-prediction-on-heterogeneous-graphs-with-pyg-6d5c29677c70

**Comment by boersmamarcel** [comment]
https://pytorch-geometric.readthedocs.io/en/latest/tutorial/create_gnn.html?highlight=gcn
