### ISSUE TITLE
Add Dataset: Stock ticker dataset (StockFormer model)

### ISSUE THREAD

**Issue by boersmamarcel** [AI4FinTech/FinTorch#64]
### Dataset Description

We aim to implements the StockFormer: A Swing Trading Strategy Based on STL Decomposition and Self-Attention Networks model. To reproduce the results, we must implement the dataset provided by the authors.

Sharing: we share the data via HuggingFace to make it easy to download it and get started with the model.
Source: https://drive.google.com/drive/folders/1V-qq2NtCV0T4ULgYLI05Ev8g5ntoC3io
Alternative source: https://pypi.org/project/yfinance/

### Tasks

- [X] Download/Extraction Script
- [ ] Dataset Test
- [X] Tutorial
- [ ] cli support

### Additional Considerations

Versioning: not supported
Documentation: basic documentation of the dataset

### license

yes

### Submission Checklist

- [ ] I have read the contribution guidelines.
- [ ] I have provided a thorough dataset description.
- [ ] My scripts and tests work as intended.
- [ ] The tutorial demonstrates dataset usage clearly.

**Comment by boersmamarcel** [comment]
Store timeseries as: https://pytorch-forecasting.readthedocs.io/en/stable/api/pytorch_forecasting.data.timeseries.TimeSeriesDataSet.html
