### ISSUE TITLE
Add Model: StockFormer

### ISSUE THREAD

**Issue by boersmamarcel** [AI4FinTech/FinTorch#65]
### Model Description

Stockformer is a deep learning framework that combines a time series decomposition method (STL) with self-attention networks and graph neural networks (GATs) to predict stock returns.

References
[StockFormer](https://arxiv.org/html/2401.06139v1)
[StockFormer GitHub by authors](https://github.com/Eric991005/Stockformer)

### Tasks

- [ ] Model saving/loading script
- [X] Model inference script (API or example)
- [X] Model performance evaluation script
- [X] Tutorial demonstrating usage

### Additional Considerations

Training set is issue #

### license

yes

### Submission Checklist

- [X] I have read the contribution guidelines.
- [ ] I have provided a detailed model description.
- [ ] All required scripts are provided, functional, and tested.
- [ ] I have clarified dependencies and hardware considerations.
- [ ] The tutorial is clear and demonstrates model usage.

**Comment by boersmamarcel** [comment]
I did some work on it, but the authors' code base uses pre-loaded models from files. See, for example, the [correlation graph](https://github.com/Eric991005/Stockformer/tree/master/data/STOCK) which is a fixed correlation graph for that particular dataset.  Hence, I am not in favor of implementing it in this code base. We might want to revisit the model at a later stage.
